#!/usr/bin/env python3
"""
Generate public_key.h from a base64-encoded OpenHaystack public key.

Usage:
    python3 binary.py [BASE64_KEY]

If no argument is supplied the key is read from the BASE64_KEY environment
variable, or the built-in default is used as a fallback.
"""

import base64
import os
import sys

# ── Key source (edit or override via env / CLI) ──────────────────────────────
# 28 zero-bytes encoded as base64 – an obvious placeholder.
# Always override this with your real key:
#   python3 binary.py <your-base64-key>
#   BASE64_KEY=<your-base64-key> make
DEFAULT_KEY = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"  # 28 × 0x00

b64_str = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("BASE64_KEY", DEFAULT_KEY)
raw_bytes = base64.b64decode(b64_str)

# ── Emit header ───────────────────────────────────────────────────────────────
hex_values = ", ".join(f"0x{b:02x}" for b in raw_bytes)

header = f"""\
/* public_key.h – AUTO-GENERATED by binary.py. DO NOT EDIT.
 *
 * Source key (base64): {b64_str}
 */
#ifndef PUBLIC_KEY_H
#define PUBLIC_KEY_H

#include <stdint.h>

static const uint8_t OFFLINE_FINDING_PUBLIC_KEY[{len(raw_bytes)}] = {{
    {hex_values}
}};

#endif /* PUBLIC_KEY_H */
"""

out_path = os.path.join(os.path.dirname(__file__), "public_key.h")
with open(out_path, "w") as f:
    f.write(header)

print(f"Generated {out_path} ({len(raw_bytes)} bytes)")